### ISSUE TITLE
Incompatibility with the TOI system

### ISSUE THREAD

**Issue by stevenpeng1116** [shadden/TTV2Fast2Furious#2]
Hi folks,
 
I’m writing this message to ask for your generous support in looking into an issue with the TTV2Fast2Furious package. Currently, I’m working on constraining the mass and eccentricity of potential perturbers in TOI multi-planetary systems by following the route of your excellent work on KOI systems. However, when I tried to apply your jupyter notebook example of "CompanionMassLimits.ipynb" and "Kepler-307-TTVs.ipynb", it seemed that the TOI system was not compatible with your code. More specifically, since there was no previously defined python script like kepler.py to obtain the TOI observation list, I just used the PlanetTransitObservations module to return the required observation list for the TransitTimesLinearModels module, but the output always reported the error as “TypeError: ‘PlanetTransitObservations’ object is not iterable”. Also, it turned out that the limits array was 0-dimensional, which indicated again that there might be something wrong with the observation list returned by the PlanetTransitObservations module. Hence, I would be grateful if you could provide me with your precious suggestions on how to fix this issue or revise your code to make it also work for the TOI system. To help you better understand where my issue lies, I have attached the corresponding section of my code to this message. Please feel free to review it whenever you have time. I appreciate your help so much!
 
Kind Regards,
 
Peifeng

[TTV2F2F_companion.txt](https://github.com/user-attachments/files/18070708/TTV2F2F_companion.txt)

**Comment by shadden** [comment]
Hello Peifeng—
 I’m traveling this week and next so I might not have time to look at this closely. If I forget to get back to you after that, please feel free to ping me again

**Comment by stevenpeng1116** [comment]
Dear Dr. Hadden,

I hope you have enjoyed your trip and the following Christmas holiday!

I'm writing this follow-up message just to see if you could now have time to look into this issue. I still haven't received your reply, and I would be grateful if you could help me solve this issue at your convenience. I appreciate your help so much!

Kind Regards,

Peifeng

> Hello Peifeng—
>  I’m traveling this week and next so I might not have time to look at this closely. If I forget to get back to you after that, please feel free to ping me again
> […](#)
>

**Comment by shadden** [comment]
Hi Peifeng— 
	The code you sent is rather complicated, making it difficult for me to follow what’s going on and identify the source of the error. In order for me to help isolate what’s going on, it would be helpful if you could do a few things:

 (1) Install the updated version of the code. You should be able to do this with 'pip install —upgrade ttv2fast2furious’. I’ve made some updates in order to make it compatible with the latest versions of numpy and scipy

(2) Confirm that the included Jupyter example notebooks run.

(3) Create a minimum working example that reproduces the error you’re getting when trying to apply the code to your TOI system

**Comment by stevenpeng1116** [comment]
Dear Dr. Hadden,

Many thanks for your reply. I just tried to upgrade ttv2fast2furious and re-ran my code, but it still didn't work on my machine. The example Jupyter notebook worked well on my machine previously, so I don't think there is anything wrong with the given example. I'm sorry to make you feel confused about my code, but that's the simplest version I can create. To help you decompose the source of errors, you can focus on the line that defines the observation object in my attached code. Although I've explained it in my original thread, I would like to explain it again in more detail. As far as I know, no one has ever collected the table of transit times for TOI systems. Hence, in order to similarly create the KOISystemObservations(KOINumber) module that works for KOI systems, I directly applied the code PlanetTransitObservations.from_times_only(times) to initialize transit observation object directly from the list of transit times. You can track what I did under the TOISystemObservations(toi) module I defined in my code. However, when I further applied the obtained observation object for TOI systems to the TransitTimesLinearModels module, it always reported some errors. The latest error I got is as follows:

Traceback (most recent call last):
  File "/nfsdata1/p.peifeng/TTVFast_MCMC_reversed.py", line 1248, in <module>
    linear_models = TransitTimesLinearModels(list(observations), planet_names='bc')
  File "/nfsdata1/p.peifeng/allesfitter/lib/python3.9/site-packages/ttv2fast2furious/ttv2fast2furious.py", line 654, in __init__
    assert np.all(obs.transit_numbers>=0), errmsg1
AttributeError: 'str' object has no attribute 'transit_numbers'

I do think this issue can be solved if the observation object for TOI systems follows the correct form as the one obtained after running the KOISystemObservations(KOINumber) module. I'm looking forward to seeing your further advice soon!

Kind Regards,

Peifeng

> Hi Peifeng—
> 	The code you sent is rather complicated, making it difficult for me to follow what’s going on and identify the source of the error. In order for me to help isolate what’s going on, it would be helpful if you could do a few things:
> 
>  (1) Install the updated version of the code. You should be able to do this with 'pip install —upgrade ttv2fast2furious’. I’ve made some updates in order to make it compatible with the latest versions of numpy and scipy
> 
> (2) Confirm that the included Jupyter example notebooks run.
> 
> (3) Create a minimum working example that reproduces the error you’re getting when trying to apply the code to your TOI system
> […](#)

**Comment by shadden** [comment]
You really need to make a simpler example reproducing the error. The code you sent me imports a number of packages that are unused, has variables that are undefined (e.g., `masses_q16 = [mass_b_q16, mass_c_q16]
masses_q50 = [mass_b_q50, mass_c_q50]
masses_q84 = [mass_b_q84, mass_c_q84]
periods = [Pb, Pc]`), uses the undefined function `ParamsToTransitTimes`, and is just generally difficult to parse. My guess is that whatever is being passed to the `PlanetTransitObservations.from_times_only` function does not have the correct format, but I can't diagnose this unless I can reproduce the error. I suggest recreating your example with a few hard-coded transit times or something.

**Comment by stevenpeng1116** [comment]
Dear Dr. Hadden,

Alright I see. I'm sorry I didn't realize that you would like to reproduce the error. I have just revised my code to make sure it can run smoothly on my machine until the line where an error was reported, please find the updated and simplified version in the attached file. Below is the reported error this time:

Traceback (most recent call last):
  File "/nfsdata1/p.peifeng/TTV2F2F_companion.py", line 65, in <module>
    ax[0].semilogy(period_ratios,limits_b[:,i]/3e-6,'-x',label=" $%d\sigma$"%(i+1))
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

If you could reproduce this error on your machine, that means at least we are at the same stage and we can potentially move forward to diagnose how the error was produced.

Kind Regards,

Peifeng

[TTV2F2F_companion.txt](https://github.com/user-attachments/files/18527809/TTV2F2F_companion.txt)

> You really need to make a simpler example reproducing the error. The code you sent me imports a number of packages that are unused, has variables that are undefined (e.g., `masses_q16 = [mass_b_q16, mass_c_q16] masses_q50 = [mass_b_q50, mass_c_q50] masses_q84 = [mass_b_q84, mass_c_q84] periods = [Pb, Pc]`), uses the undefined function `ParamsToTransitTimes`, and is just generally difficult to parse. My guess is that whatever is being passed to the `PlanetTransitObservations.from_times_only` function does not have the correct format, but I can't diagnose this unless I can reproduce the error. I suggest recreating your example with a few hard-coded transit times or something.

**Comment by shadden** [comment]
The example you sent was still quite complicated, but I found at least a few issues:
 - The argument to `PlanetTransitObservations.from_times_only` needs to be a numpy array, not a list
 -  A nonzero uncertainty needs to be specified when initializing a `PlanetTransitObservations.from_times_only`
 - You were passing a dictionary to `UnseenPerturberMassUpperLimit` as the third argument, whereas a `PlanetTransitObservations` is called for.

I should probably update the code to raise exceptions when improper input is past to functions, but this is not something I'm likely to get around to in the near future 

More generally, I'm not exactly sure what you're trying to do with the code-- the `UnseenPerturberMassUpperLimit` is for placing constraints on unseen perturbers based on a lack of apparent TTVs, but you're applying it to a multi-planet system with clear TTVs. The `TransitTimesLinearModels` class is nominally the right tool for modelling TTVs in multi-planet systems, but I would caution that TOI-216 is in a 2:1 MMR, where the assumptions underlying the way the code works are not valid.

**Comment by stevenpeng1116** [comment]
Dear Dr. Hadden,

Many thanks for your detailed reply. I have followed your first and second advice, but my code still didn't work. I guess the key point is the third issue you mentioned in your comment. I'm wondering if the third argument of 'UnseenPerturberMassUpperLimit' is not a dictionary, what should it be? From your given example in the fourth and fifth boxes of 'CompanionMassLimits.ipynb', it seems that the third argument represents the observation data on the transiting planet, which I think is exactly what I'm trying to achieve in my code. My understanding is that there might be something wrong with my observation object, but I'm not sure how to correct it. Even after I marked out the first section of plotting the Companion Mass vs Companion Period Ratio graph in my code, it still reported an old error as follows:

Traceback (most recent call last):
  File "/nfsdata1/p.peifeng/TTV2F2F_companion.py", line 77, in <module>
    linear_models_b = TransitTimesLinearModels(list(observations_b), planet_names='b')
  File "/nfsdata1/p.peifeng/allesfitter/lib/python3.9/site-packages/ttv2fast2furious/ttv2fast2furious.py", line 654, in __init__
    assert np.all(obs.transit_numbers>=0), errmsg1
AttributeError: 'str' object has no attribute 'transit_numbers'

Regarding your confusion about my intention to use this code, I'm sorry I didn't know that your code only applies to systems with non-apparent TTVs. However, even though systems like TOI-216 do have apparent TTVs, it's still worth using your code to examine if there are any unseen perturbers in these systems. I'm currently working on a cataloging project, and what I can tell you is that there are many TOIs whose TTVs cannot be solely explained by the MMR. TOI-216 is one of the target systems that aroused our interest, and some of our interested systems indeed don't have apparent TTVs, which means your code is still applicable to our project. Also, as far as I know, some research groups have applied your code to put constraints on any unseen perturbers in their interested TOI systems no matter whether their TTVs are apparent or not, but I still don't know how they achieved this.

Anyway, please feel free to review my updated codes attached below. If you can reproduce the error I mentioned above, that means I definitely made some mistakes when I was trying to define 'TOISystemObservations' in my code, and I would be grateful if you could let me know how to correct this issue at your convenience.

Kind Regards,

Peifeng

[TTV2F2F_companion.txt](https://github.com/user-attachments/files/18543113/TTV2F2F_companion.txt)

> The example you sent was still quite complicated, but I found at least a few issues:
> 
> * The argument to `PlanetTransitObservations.from_times_only` needs to be a numpy array, not a list
> * A nonzero uncertainty needs to be specified when initializing a `PlanetTransitObservations.from_times_only`
> * You were passing a dictionary to `UnseenPerturberMassUpperLimit` as the third argument, whereas a `PlanetTransitObservations` is called for.
> 
> I should probably update the code to raise exceptions when improper input is past to functions, but this is not something I'm likely to get around to in the near future
> 
> More generally, I'm not exactly sure what you're trying to do with the code-- the `UnseenPerturberMassUpperLimit` is for placing constraints on unseen perturbers based on a lack of apparent TTVs, but you're applying it to a multi-planet system with clear TTVs. The `TransitTimesLinearModels` class is nominally the right tool for modelling TTVs in multi-planet systems, but I would caution that TOI-216 is in a 2:1 MMR, where the assumptions underlying the way the code works are not valid.

**Comment by stevenpeng1116** [comment]
Dear Dr. Hadden,

After diligently debugging my code, I'm glad to inform you that I finally made it work today! I just replaced the second part of my code with your code in box 11 of the "Kepler-307-TTVs.ipynb" Jupyter example because I didn't realize that you just updated it several days ago. Although my code still didn't work to plot the Companion Mass vs Companion Period Ratio graph, at least now it works to plot the mass-eccentricity constraints graph. I have attached my corrected codes below for review by those who are interested in how I made mistakes. I will now close this comment if necessary.

Kind Regards,

Peifeng

[TTV2F2F_companion.txt](https://github.com/user-attachments/files/18583922/TTV2F2F_companion.txt)

> Dear Dr. Hadden,
> 
> Many thanks for your detailed reply. I have followed your first and second advice, but my code still didn't work. I guess the key point is the third issue you mentioned in your comment. I'm wondering if the third argument of 'UnseenPerturberMassUpperLimit' is not a dictionary, what should it be? From your given example in the fourth and fifth boxes of 'CompanionMassLimits.ipynb', it seems that the third argument represents the observation data on the transiting planet, which I think is exactly what I'm trying to achieve in my code. My understanding is that there might be something wrong with my observation object, but I'm not sure how to correct it. Even after I marked out the first section of plotting the Companion Mass vs Companion Period Ratio graph in my code, it still reported an old error as follows:
> 
> Traceback (most recent call last): File "/nfsdata1/p.peifeng/TTV2F2F_companion.py", line 77, in linear_models_b = TransitTimesLinearModels(list(observations_b), planet_names='b') File "/nfsdata1/p.peifeng/allesfitter/lib/python3.9/site-packages/ttv2fast2furious/ttv2fast2furious.py", line 654, in **init** assert np.all(obs.transit_numbers>=0), errmsg1 AttributeError: 'str' object has no attribute 'transit_numbers'
> 
> Regarding your confusion about my intention to use this code, I'm sorry I didn't know that your code only applies to systems with non-apparent TTVs. However, even though systems like TOI-216 do have apparent TTVs, it's still worth using your code to examine if there are any unseen perturbers in these systems. I'm currently working on a cataloging project, and what I can tell you is that there are many TOIs whose TTVs cannot be solely explained by the MMR. TOI-216 is one of the target systems that aroused our interest, and some of our interested systems indeed don't have apparent TTVs, which means your code is still applicable to our project. Also, as far as I know, some research groups have applied your code to put constraints on any unseen perturbers in their interested TOI systems no matter whether their TTVs are apparent or not, but I still don't know how they achieved this.
> 
> Anyway, please feel free to review my updated codes attached below. If you can reproduce the error I mentioned above, that means I definitely made some mistakes when I was trying to define 'TOISystemObservations' in my code, and I would be grateful if you could let me know how to correct this issue at your convenience.
> 
> Kind Regards,
> 
> Peifeng
> 
> [TTV2F2F_companion.txt](https://github.com/user-attachments/files/18543113/TTV2F2F_companion.txt)
> 
> > The example you sent was still quite complicated, but I found at least a few issues:
> > 
> > * The argument to `PlanetTransitObservations.from_times_only` needs to be a numpy array, not a list
> > * A nonzero uncertainty needs to be specified when initializing a `PlanetTransitObservations.from_times_only`
> > * You were passing a dictionary to `UnseenPerturberMassUpperLimit` as the third argument, whereas a `PlanetTransitObservations` is called for.
> > 
> > I should probably update the code to raise exceptions when improper input is past to functions, but this is not something I'm likely to get around to in the near future
> > More generally, I'm not exactly sure what you're trying to do with the code-- the `UnseenPerturberMassUpperLimit` is for placing constraints on unseen perturbers based on a lack of apparent TTVs, but you're applying it to a multi-planet system with clear TTVs. The `TransitTimesLinearModels` class is nominally the right tool for modelling TTVs in multi-planet systems, but I would caution that TOI-216 is in a 2:1 MMR, where the assumptions underlying the way the code works are not valid.

**Comment by stevenpeng1116** [comment]
Dear Dr. Hadden,

I'm glad to inform you that I just finished debugging all the issues in my code. You are definitely right that the third argument of 'UnseenPerturberMassUpperLimit' should not be a dictionary, instead it should just be the original observation object obtained after running the 'PlanetTransitObservations.from_times_only' function. I can now confidently close this comment, and I really appreciate your generous help in my debugging process!

For those who might be interested in how my code finally works, please feel free to check it out below.

Kind Regards,

Peifeng

[TTV2F2F_companion_updated.txt](https://github.com/user-attachments/files/18608433/TTV2F2F_companion_updated.txt)

> Dear Dr. Hadden,
> 
> After diligently debugging my code, I'm glad to inform you that I finally made it work today! I just replaced the second part of my code with your code in box 11 of the "Kepler-307-TTVs.ipynb" Jupyter example because I didn't realize that you just updated it several days ago. Although my code still didn't work to plot the Companion Mass vs Companion Period Ratio graph, at least now it works to plot the mass-eccentricity constraints graph. I have attached my corrected codes below for review by those who are interested in how I made mistakes. I will now close this comment if necessary.
> 
> Kind Regards,
> 
> Peifeng
> 
> [TTV2F2F_companion.txt](https://github.com/user-attachments/files/18583922/TTV2F2F_companion.txt)
> 
> > Dear Dr. Hadden,
> > Many thanks for your detailed reply. I have followed your first and second advice, but my code still didn't work. I guess the key point is the third issue you mentioned in your comment. I'm wondering if the third argument of 'UnseenPerturberMassUpperLimit' is not a dictionary, what should it be? From your given example in the fourth and fifth boxes of 'CompanionMassLimits.ipynb', it seems that the third argument represents the observation data on the transiting planet, which I think is exactly what I'm trying to achieve in my code. My understanding is that there might be something wrong with my observation object, but I'm not sure how to correct it. Even after I marked out the first section of plotting the Companion Mass vs Companion Period Ratio graph in my code, it still reported an old error as follows:
> > Traceback (most recent call last): File "/nfsdata1/p.peifeng/TTV2F2F_companion.py", line 77, in linear_models_b = TransitTimesLinearModels(list(observations_b), planet_names='b') File "/nfsdata1/p.peifeng/allesfitter/lib/python3.9/site-packages/ttv2fast2furious/ttv2fast2furious.py", line 654, in **init** assert np.all(obs.transit_numbers>=0), errmsg1 AttributeError: 'str' object has no attribute 'transit_numbers'
> > Regarding your confusion about my intention to use this code, I'm sorry I didn't know that your code only applies to systems with non-apparent TTVs. However, even though systems like TOI-216 do have apparent TTVs, it's still worth using your code to examine if there are any unseen perturbers in these systems. I'm currently working on a cataloging project, and what I can tell you is that there are many TOIs whose TTVs cannot be solely explained by the MMR. TOI-216 is one of the target systems that aroused our interest, and some of our interested systems indeed don't have apparent TTVs, which means your code is still applicable to our project. Also, as far as I know, some research groups have applied your code to put constraints on any unseen perturbers in their interested TOI systems no matter whether their TTVs are apparent or not, but I still don't know how they achieved this.
> > Anyway, please feel free to review my updated codes attached below. If you can reproduce the error I mentioned above, that means I definitely made some mistakes when I was trying to define 'TOISystemObservations' in my code, and I would be grateful if you could let me know how to correct this issue at your convenience.
> > Kind Regards,
> > Peifeng
> > [TTV2F2F_companion.txt](https://github.com/user-attachments/files/18543113/TTV2F2F_companion.txt)
> > > The example you sent was still quite complicated, but I found at least a few issues:
> > > 
> > > * The argument to `PlanetTransitObservations.from_times_only` needs to be a numpy array, not a list
> > > * A nonzero uncertainty needs to be specified when initializing a `PlanetTransitObservations.from_times_only`
> > > * You were passing a dictionary to `UnseenPerturberMassUpperLimit` as the third argument, whereas a `PlanetTransitObservations` is called for.
> > > 
> > > I should probably update the code to raise exceptions when improper input is past to functions, but this is not something I'm likely to get around to in the near future
> > > More generally, I'm not exactly sure what you're trying to do with the code-- the `UnseenPerturberMassUpperLimit` is for placing constraints on unseen perturbers based on a lack of apparent TTVs, but you're applying it to a multi-planet system with clear TTVs. The `TransitTimesLinearModels` class is nominally the right tool for modelling TTVs in multi-planet systems, but I would caution that TOI-216 is in a 2:1 MMR, where the assumptions underlying the way the code works are not valid.
